{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['source_id', 'cleaned_metadatas', 'generated_metadatas', 'source_url',\\n       'Value Pillar'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['source_id', 'cleaned_metadatas', 'generated_metadatas', 'source_url',\\n       'Value Pillar'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['source_id', 'cleaned_metadatas', 'generated_metadatas', 'source_url',\\n       'Value Pillar'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas', 'source_id',\\n       'source_url'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['source_url', 'cleaned_metadatas', 'generated_metadatas',\\n       'Value Pillar', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas',\\n       'source_url', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas',\\n       'source_url', 'source_id'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['generated_metadatas', 'Value Pillar', 'cleaned_metadatas',\\n       'source_url', 'source_id'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['source_id', 'Value Pillar', 'source_url', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['source_id', 'Value Pillar', 'source_url', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['source_id', 'Value Pillar', 'source_url', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
{
    "type": "error",
    "data": "Error executing verb \"create_final_documents\" in create_final_documents: \"None of [Index(['Value Pillar', 'source_url', 'source_id', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"",
    "stack": "Traceback (most recent call last):\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/datashaper/workflow/workflow.py\", line 415, in _execute_verb\n    result = await result\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/workflows/v1/create_final_documents.py\", line 65, in workflow\n    output = create_final_documents(source, text_units, document_attribute_columns)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/graphrag/index/flows/create_final_documents.py\", line 52, in create_final_documents\n    rejoined[document_attribute_columns] = rejoined[\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/frame.py\", line 4108, in __getitem__\n    indexer = self.columns._get_indexer_strict(key, \"columns\")[1]\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6200, in _get_indexer_strict\n    self._raise_if_missing(keyarr, indexer, axis_name)\n  File \"/Users/abdelmajidboubrik/Library/DataScienceStudio/dss_home/code-envs/python/graphrag/lib/python3.10/site-packages/pandas/core/indexes/base.py\", line 6249, in _raise_if_missing\n    raise KeyError(f\"None of [{key}] are in the [{axis_name}]\")\nKeyError: \"None of [Index(['Value Pillar', 'source_url', 'source_id', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"\n",
    "source": "\"None of [Index(['Value Pillar', 'source_url', 'source_id', 'cleaned_metadatas',\\n       'generated_metadatas'],\\n      dtype='object')] are in the [columns]\"",
    "details": null
}
